# H2 database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:testdb

# Spring Security, OAuth2, Keycloak setup
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/dmit2015-realm
# Tells Spring Boot to look for the "preferred_username" inside the JWT to identify the user
spring.security.oauth2.resourceserver.jwt.principal-claim-name=preferred_username